<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Domain\DTOs\"/>
        <Folder Include="Domain\Interfaces\" />
        <Folder Include="Domain\Models\" />
        <Folder Include="Domain\Strategies\" />
        <Folder Include="Infrastructure\Mappers\"/>
        <Folder Include="Infrastructure\Services\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Database\Database.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj"/>
    </ItemGroup>

</Project>
