// <auto-generated />
using System;
using Database.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402194545_AddPictureMetadata")]
    partial class AddPictureMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Database.Domain.Entities.Metrics", b =>
                {
                    b.Property<int>("PictureId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PHash")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sharpness")
                        .HasColumnType("INTEGER");

                    b.HasKey("PictureId");

                    b.ToTable("metrics", (string)null);
                });

            modelBuilder.Entity("Database.Domain.Entities.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Name", "Type")
                        .IsUnique();

                    b.ToTable("nodes", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Database.Domain.Entities.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupingThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LaunchMaximized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThemeMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupingThreshold = 5,
                            LaunchMaximized = false,
                            LibraryPath = "",
                            ThemeMode = 0
                        });
                });

            modelBuilder.Entity("Database.Domain.Entities.Album", b =>
                {
                    b.HasBaseType("Database.Domain.Entities.Node");

                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("Database.Domain.Entities.Folder", b =>
                {
                    b.HasBaseType("Database.Domain.Entities.Node");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Database.Domain.Entities.Picture", b =>
                {
                    b.HasBaseType("Database.Domain.Entities.Node");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Hash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sharpness")
                        .HasColumnType("INTEGER");

                    b.ToTable("pictures", (string)null);
                });

            modelBuilder.Entity("Database.Domain.Entities.Metrics", b =>
                {
                    b.HasOne("Database.Domain.Entities.Picture", "Picture")
                        .WithOne("Metrics")
                        .HasForeignKey("Database.Domain.Entities.Metrics", "PictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("Database.Domain.Entities.Node", b =>
                {
                    b.HasOne("Database.Domain.Entities.Node", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Database.Domain.Entities.Album", b =>
                {
                    b.HasOne("Database.Domain.Entities.Node", null)
                        .WithOne()
                        .HasForeignKey("Database.Domain.Entities.Album", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Domain.Entities.Folder", b =>
                {
                    b.HasOne("Database.Domain.Entities.Node", null)
                        .WithOne()
                        .HasForeignKey("Database.Domain.Entities.Folder", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Domain.Entities.Picture", b =>
                {
                    b.HasOne("Database.Domain.Entities.Node", null)
                        .WithOne()
                        .HasForeignKey("Database.Domain.Entities.Picture", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Domain.Entities.Node", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Database.Domain.Entities.Picture", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
