// <auto-generated />
using System;
using Database.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260728153211_AddColorLabelShortcuts")]
    partial class AddColorLabelShortcuts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Database.Domain.Entities.Metrics", b =>
                {
                    b.Property<int>("PictureId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PHash")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sharpness")
                        .HasColumnType("INTEGER");

                    b.HasKey("PictureId");

                    b.ToTable("metrics", (string)null);
                });

            modelBuilder.Entity("Database.Domain.Entities.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Name", "Type")
                        .IsUnique();

                    b.ToTable("nodes", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Database.Domain.Entities.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlueLabelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlueLabelShortcut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BurstFallbackTimeThresholdSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BurstTimeThresholdSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EditFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GreenLabelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GreenLabelShortcut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupingThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LaunchMaximized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoneLabelShortcut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrangeLabelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrangeLabelShortcut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PinkLabelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PinkLabelShortcut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PurpleLabelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PurpleLabelShortcut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RedLabelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RedLabelShortcut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThemeMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YellowLabelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YellowLabelShortcut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlueLabelName = "Blue",
                            BlueLabelShortcut = "Ctrl+NumPad5",
                            BurstFallbackTimeThresholdSeconds = 10,
                            BurstTimeThresholdSeconds = 3,
                            EditFolderPath = "",
                            GreenLabelName = "Green",
                            GreenLabelShortcut = "Ctrl+NumPad4",
                            GroupingThreshold = 8,
                            LaunchMaximized = false,
                            LibraryPath = "",
                            NoneLabelShortcut = "Ctrl+NumPad0",
                            OrangeLabelName = "Orange",
                            OrangeLabelShortcut = "Ctrl+NumPad2",
                            PinkLabelName = "Pink",
                            PinkLabelShortcut = "Ctrl+NumPad6",
                            PrintFolderPath = "",
                            PurpleLabelName = "Purple",
                            PurpleLabelShortcut = "Ctrl+NumPad7",
                            RedLabelName = "Red",
                            RedLabelShortcut = "Ctrl+NumPad1",
                            ThemeMode = 0,
                            YellowLabelName = "Yellow",
                            YellowLabelShortcut = "Ctrl+NumPad3"
                        });
                });

            modelBuilder.Entity("Database.Domain.Entities.Album", b =>
                {
                    b.HasBaseType("Database.Domain.Entities.Node");

                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("Database.Domain.Entities.Folder", b =>
                {
                    b.HasBaseType("Database.Domain.Entities.Node");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Database.Domain.Entities.Picture", b =>
                {
                    b.HasBaseType("Database.Domain.Entities.Node");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .HasColumnType("TEXT");

                    b.Property<long>("Hash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sharpness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.ToTable("pictures", (string)null);
                });

            modelBuilder.Entity("Database.Domain.Entities.Metrics", b =>
                {
                    b.HasOne("Database.Domain.Entities.Picture", "Picture")
                        .WithOne("Metrics")
                        .HasForeignKey("Database.Domain.Entities.Metrics", "PictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("Database.Domain.Entities.Node", b =>
                {
                    b.HasOne("Database.Domain.Entities.Node", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Database.Domain.Entities.Album", b =>
                {
                    b.HasOne("Database.Domain.Entities.Node", null)
                        .WithOne()
                        .HasForeignKey("Database.Domain.Entities.Album", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Domain.Entities.Folder", b =>
                {
                    b.HasOne("Database.Domain.Entities.Node", null)
                        .WithOne()
                        .HasForeignKey("Database.Domain.Entities.Folder", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Domain.Entities.Picture", b =>
                {
                    b.HasOne("Database.Domain.Entities.Node", null)
                        .WithOne()
                        .HasForeignKey("Database.Domain.Entities.Picture", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Domain.Entities.Node", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Database.Domain.Entities.Picture", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
