using System.IO.Abstractions;
using Database.Domain.Entities;
using Domain.Enums;
using Graph.Domain.Interfaces;

namespace Graph.Infrastructure.Services;

public class AlbumService(INodeService nodeService, IFileSystem fileSystem) : IAlbumService {
    public async Task<Album> CreateAsync(int? parentId, string albumName, string path) {
        var album = new Album {
            Name = albumName,
            ParentId = parentId,
            Type = NodeType.Album
        };

        // NodeService will call AlbumCreationStrategy.Prepare(album), which generates the UUID
        await nodeService.CreateNodeAsync(album);

        // Now that the UUID is generated and persisted, create the physical directory
        if (string.IsNullOrEmpty(album.Uuid)) {
            throw new InvalidOperationException("Album UUID was not generated by the creation strategy.");
        }

        var albumPath = fileSystem.Path.Combine(path, album.Uuid);
        fileSystem.Directory.CreateDirectory(albumPath);

        // Create the standard subdirectories
        fileSystem.Directory.CreateDirectory(fileSystem.Path.Combine(albumPath, "RAWs"));
        fileSystem.Directory.CreateDirectory(fileSystem.Path.Combine(albumPath, "JPGs"));
        fileSystem.Directory.CreateDirectory(fileSystem.Path.Combine(albumPath, "Thumbnails"));
        fileSystem.Directory.CreateDirectory(fileSystem.Path.Combine(albumPath, "Picked"));

        return album;
    }
}
