using System.IO.Abstractions;
using Database.Domain.Entities;
using Database.Domain.Interfaces;
using Domain.Enums;
using Domain.Interfaces;
using Graph.Domain.Interfaces;

namespace Graph.Infrastructure.Services;

public class AlbumService(
    INodeService nodeService,
    IFileSystem fileSystem,
    ISettingsService settingsService,
    IPictureRepository pictureRepository,
    IPathService pathService) : IAlbumService {
    public async Task<Album> CreateAsync(int? parentId, string albumName, string path) {
        var album = new Album {
            Name = albumName,
            ParentId = parentId,
            Type = NodeType.Album
        };

        // NodeService will call AlbumCreationStrategy.Prepare(album), which generates the UUID
        await nodeService.CreateNodeAsync(album);

        // Now that the UUID is generated and persisted, create the physical directory
        if (string.IsNullOrEmpty(album.Uuid)) {
            throw new InvalidOperationException("Album UUID was not generated by the creation strategy.");
        }

        var albumPath = fileSystem.Path.Combine(path, album.Uuid);
        fileSystem.Directory.CreateDirectory(albumPath);

        // Create the standard subdirectories
        fileSystem.Directory.CreateDirectory(fileSystem.Path.Combine(albumPath, "RAWs"));
        fileSystem.Directory.CreateDirectory(fileSystem.Path.Combine(albumPath, "JPGs"));
        fileSystem.Directory.CreateDirectory(fileSystem.Path.Combine(albumPath, "Thumbnails"));
        fileSystem.Directory.CreateDirectory(fileSystem.Path.Combine(albumPath, "Picked"));

        return album;
    }

    public async Task DeleteAsync(Album album) {
        var settings = settingsService.Current;
        var libraryPath = settings.LibraryPath;

        if (string.IsNullOrEmpty(libraryPath)) {
            throw new InvalidOperationException("Library path is not configured.");
        }

        if (string.IsNullOrEmpty(album.Uuid)) {
            throw new InvalidOperationException("Album UUID is missing.");
        }

        var sourcePath = fileSystem.Path.Combine(libraryPath, album.Uuid);
        var deletedRoot = fileSystem.Path.Combine(libraryPath, "deleted");
        var destinationPath = fileSystem.Path.Combine(deletedRoot, album.Uuid);

        if (fileSystem.Directory.Exists(sourcePath)) {
            if (!fileSystem.Directory.Exists(deletedRoot)) {
                fileSystem.Directory.CreateDirectory(deletedRoot);
            }

            // Move the directory to the retention path
            fileSystem.Directory.Move(sourcePath, destinationPath);
        }

        await nodeService.DeleteNodeAsync(album);
    }

    public async Task SyncPickedStatusAsync(Album album) {
        var pickedPath = pathService.GetAlbumPickedPath(album);
        if (string.IsNullOrEmpty(pickedPath) || !fileSystem.Directory.Exists(pickedPath)) {
            return;
        }

        var pickedFiles = fileSystem.Directory.GetFiles(pickedPath);
        var pickedFileNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var file in pickedFiles) {
            var fileNameWithoutExtension = fileSystem.Path.GetFileNameWithoutExtension(file);
            pickedFileNames.Add(fileNameWithoutExtension);
        }

        var pictures = await pictureRepository.FindByHierarchyIdAsync(album.Id);

        foreach (var picture in pictures) {
            bool isPickedOnDisk = pickedFileNames.Contains(picture.Name);
            bool isFlaggedInDb = picture.CurationStatus == CurationStatus.Flagged;

            if (isPickedOnDisk && !isFlaggedInDb) {
                picture.CurationStatus = CurationStatus.Flagged;
                await pictureRepository.UpdateAsync(picture);
            } else if (!isPickedOnDisk && isFlaggedInDb) {
                picture.CurationStatus = CurationStatus.Unflagged;
                await pictureRepository.UpdateAsync(picture);
            }
        }
    }
}
