using System.IO.Abstractions;
using Database.Domain.Entities;
using Database.Domain.Interfaces;
using Domain.Enums;
using Domain.Interfaces;
using Graph.Domain.Interfaces;

namespace Graph.Infrastructure.Services;

public class AlbumService(
    INodeService nodeService,
    IFileSystem fileSystem,
    ISettingsService settingsService,
    IPictureRepository pictureRepository,
    IPathService pathService,
    IXmpService xmpService) : IAlbumService {
    public async Task<Album> CreateAsync(int? parentId, string albumName, string path) {
        var album = new Album {
            Name = albumName,
            ParentId = parentId,
            Type = NodeType.Album
        };

        // NodeService will call AlbumCreationStrategy.Prepare(album), which generates the UUID
        await nodeService.CreateNodeAsync(album);

        // Now that the UUID is generated and persisted, create the physical directory
        if (string.IsNullOrEmpty(album.Uuid)) {
            throw new InvalidOperationException("Album UUID was not generated by the creation strategy.");
        }

        var albumPath = fileSystem.Path.Combine(path, album.Uuid);
        fileSystem.Directory.CreateDirectory(albumPath);

        // Create the standard subdirectories
        fileSystem.Directory.CreateDirectory(fileSystem.Path.Combine(albumPath, "RAWs"));
        fileSystem.Directory.CreateDirectory(fileSystem.Path.Combine(albumPath, "JPGs"));
        fileSystem.Directory.CreateDirectory(fileSystem.Path.Combine(albumPath, "Thumbnails"));
        fileSystem.Directory.CreateDirectory(fileSystem.Path.Combine(albumPath, "Picked"));

        return album;
    }

    public async Task DeleteAsync(Album album) {
        var settings = settingsService.Current;
        var libraryPath = settings.LibraryPath;

        if (string.IsNullOrEmpty(libraryPath)) {
            throw new InvalidOperationException("Library path is not configured.");
        }

        if (string.IsNullOrEmpty(album.Uuid)) {
            throw new InvalidOperationException("Album UUID is missing.");
        }

        var sourcePath = fileSystem.Path.Combine(libraryPath, album.Uuid);
        var deletedRoot = fileSystem.Path.Combine(libraryPath, "deleted");
        var destinationPath = fileSystem.Path.Combine(deletedRoot, album.Uuid);

        if (fileSystem.Directory.Exists(sourcePath)) {
            if (!fileSystem.Directory.Exists(deletedRoot)) {
                fileSystem.Directory.CreateDirectory(deletedRoot);
            }

            // Move the directory to the retention path
            fileSystem.Directory.Move(sourcePath, destinationPath);
        }

        await nodeService.DeleteNodeAsync(album);
    }

    public async Task SyncPickedStatusAsync(Album album) {
        var pickedPath = pathService.GetAlbumPickedPath(album);
        if (string.IsNullOrEmpty(pickedPath) || !fileSystem.Directory.Exists(pickedPath)) {
            return;
        }

        var pickedFiles = fileSystem.Directory.GetFiles(pickedPath);
        var pickedFileNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var file in pickedFiles) {
            var fileNameWithoutExtension = fileSystem.Path.GetFileNameWithoutExtension(file);
            pickedFileNames.Add(fileNameWithoutExtension);
        }

        var pictures = await pictureRepository.FindByHierarchyIdAsync(album.Id);
        foreach (var picture in pictures) {
            picture.Parent = album;
        }
        pathService.PopulatePaths(pictures);

        foreach (var picture in pictures) {
            await xmpService.LoadMetadataAsync(picture);

            bool isPickedOnDisk = pickedFileNames.Contains(picture.Name);
            bool isFlagged = picture.CurationStatus == CurationStatus.Flagged;

            if (isPickedOnDisk && !isFlagged) {
                picture.CurationStatus = CurationStatus.Flagged;
                await xmpService.SaveMetadataAsync(picture);
            } else if (!isPickedOnDisk && isFlagged) {
                picture.CurationStatus = CurationStatus.Unflagged;
                await xmpService.SaveMetadataAsync(picture);
            }
        }
    }

    public async Task SyncHighlightsAsync(Album album) {
        var highlightsPath = pathService.GetAlbumHighlightsPath(album);
        if (string.IsNullOrEmpty(highlightsPath)) {
            return;
        }

        var pictures = await pictureRepository.FindByHierarchyIdAsync(album.Id);
        foreach (var picture in pictures) {
            picture.Parent = album;
        }
        pathService.PopulatePaths(pictures);

        var bluePictureNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var picture in pictures) {
            await xmpService.LoadMetadataAsync(picture);
            if (picture.ColorLabel == ColorLabel.Blue) {
                bluePictureNames.Add(picture.Name);
            }
        }

        // Ensure directory exists if we have highlights to copy
        if (bluePictureNames.Count > 0 && !fileSystem.Directory.Exists(highlightsPath)) {
            fileSystem.Directory.CreateDirectory(highlightsPath);
        }

        // Copy/overwrite blue pictures
        foreach (var picture in pictures) {
            if (picture.ColorLabel == ColorLabel.Blue) {
                var previewPath = picture.SubFolder?.Preview;
                if (!string.IsNullOrEmpty(previewPath) && fileSystem.File.Exists(previewPath)) {
                    var targetPath = fileSystem.Path.Combine(highlightsPath, picture.Name + ".jpg");

                    var directory = fileSystem.Path.GetDirectoryName(targetPath);
                    if (directory != null && !fileSystem.Directory.Exists(directory)) {
                        fileSystem.Directory.CreateDirectory(directory);
                    }

                    await Task.Run(() => fileSystem.File.Copy(previewPath, targetPath, true));
                }
            }
        }

        // Clean up files in Highlights that are no longer blue highlight pictures
        if (fileSystem.Directory.Exists(highlightsPath)) {
            var existingFiles = fileSystem.Directory.GetFiles(highlightsPath);
            foreach (var file in existingFiles) {
                var fileNameWithoutExt = fileSystem.Path.GetFileNameWithoutExtension(file);
                if (!bluePictureNames.Contains(fileNameWithoutExt)) {
                    await Task.Run(() => fileSystem.File.Delete(file));
                }
            }
        }
    }
}
