<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.2.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Database\Database.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
        <ProjectReference Include="..\Graph\Graph.csproj" />
    </ItemGroup>

</Project>
